id: ACAA03671
base_file: f58F2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:14:29.502407
  last_modified_at: 2022-05-30 23:14:29.502419
