id: ACAA03671
base_file: fFC19.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:14:29.513459
  last_modified_at: 2022-05-30 23:14:29.513462
