id: ACAA03671
base_file: f78AB.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:14:29.508821
  last_modified_at: 2022-05-30 23:14:29.508826
