id: ACAA03671
base_file: f5786.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:14:29.500360
  last_modified_at: 2022-05-30 23:14:29.500366
