id: ACAA03671
base_file: f68B4.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:14:29.505370
  last_modified_at: 2022-05-30 23:14:29.505379
